# This file was generated by GoReleaser. DO NOT EDIT.
cask "foo" do
  desc "CLI"
  homepage "https://github.com/polyium/polyforge"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polyforge"

  on_macos do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.7/polyforge-darwin-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ]
      sha256 "f8debcf4601fde0e4b009f65cdc912ca92c9032b9fc4d39d714fe47f8460f90e"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.7/polyforge-darwin-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ]
      sha256 "139e3cab1bf9218c549414fc9e1d64d740a0417d679470b841bbc214d36b4fe6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.7/polyforge-linux-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ]
      sha256 "1cb7670716932764633ef00a763500a2ecef36916bce6b74d871f8059257a671"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.7/polyforge-linux-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.7",
        ]
      sha256 "5641363ed86f0483b38fe54495bfa18fa02021d95aae0293d91169658b5990e0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
