# This file was generated by GoReleaser. DO NOT EDIT.
cask "polyforge" do
  desc "CLI"
  homepage "https://github.com/polyium/polyforge"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polyforge"

  on_macos do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.8/polyforge-darwin-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ]
      sha256 "172978b5c44e869a6657ba737547ed3ced62c0f284eb48a08888cbcfdfebd745"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.8/polyforge-darwin-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ]
      sha256 "a384808933032b2a5bf3e626a6fec911c7cfc6a8e7cc74ce932f65292501aa4d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.8/polyforge-linux-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ]
      sha256 "33e2fd35aab934c0e37fcdf174872f3860bdf362ee0eab19b0c718044bfbe925"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.8/polyforge-linux-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.8",
        ]
      sha256 "cdf62070aeca76ce67c0e9a132ff2113223088ec941ae6e029685ca747083078"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
