# This file was generated by GoReleaser. DO NOT EDIT.
cask "polyforge" do
  desc "CLI"
  homepage "https://github.com/polyium/polyforge"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polyforge"

  on_macos do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.10/polyforge-darwin-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.10",
        ]
      sha256 "1f4e8143c38062fbcef32bc02848317822edb7136106fe5543d712d02b537da7"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.10/polyforge-darwin-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.10",
        ]
      sha256 "f162ab76dd5b115ef11b7c6c5716f30b5c715c869a6765e564be767cdaa4d36e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.10/polyforge-linux-x86-64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.10",
        ]
      sha256 "fcf2d9954cbf59a53a9a4a9731c1cfa3522ec582c2ca0cd99fbe39d89b2630b4"
    end
    on_arm do
      url "https://github.com/polyium/polyforge/releases/download/v0.0.10/polyforge-linux-arm64.tar.gz",
        verified: "github.com/polyium/polyforge",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.10",
        ]
      sha256 "1a2a186afb5cb3f542697ac972ee978f1abca6c2ae46d1c23382e5f74851dc4f"
    end
  end

  # No zap stanza required
end
