# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polyforge < Formula
  desc "CLI"
  homepage "https://github.com/polyium/polyforge"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/polyium/polyforge/releases/download/v0.0.3/polyforge-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "ed4eccaf334697d9785eba6bd39e2ae084110fd4c08372dc98eb7375120d6cdf"

      def install
        bin.install "polyforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/polyium/polyforge/releases/download/v0.0.3/polyforge-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "53cb261813f840b1bf029a13144851201cbe9f5501ae660dddb9dbf7ccbd29b6"

      def install
        bin.install "polyforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/polyium/polyforge/releases/download/v0.0.3/polyforge-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "d823f24fd43abede2f455359386df040fd813a2c6c54c4ece412cd2ac3334b86"
      def install
        bin.install "polyforge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/polyium/polyforge/releases/download/v0.0.3/polyforge-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a52627a481c9badb9829b06a136b87c16968e6788122cd7200b4157056609c7c"
      def install
        bin.install "polyforge"
      end
    end
  end

  conflicts_with "polyforge"
end
